// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupExperimentPrefs.extensions.pocket.loggedOutVariant", "button_control");
user_pref("app.normandy.startupRolloutPrefs.print.tab_modal.enabled", true);
user_pref("app.normandy.user_id", "fb0a0c69-c24f-4b16-a127-10660ade0787");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1615291245);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1615291263);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1615291218);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1615291365);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1615291275);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.engagement.ctrlTab.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1615291215);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"86622\":1615291233162,\"86747\":1615291233164,\"86798\":1615291233160}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{7af87702-8524-4a7d-937e-bb95e3dd1c9a}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1615291218);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1615291273408");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1615293068408");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1615291226868");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1615312826868");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1615291218");
user_pref("browser.slowStartup.averageTime", 2443);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210222142601");
user_pref("browser.startup.homepage_override.mstone", "86.0");
user_pref("browser.startup.lastColdStartupCheck", 1615291217);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1615291224005");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "86.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "16617facf9b94f3783a170ec55dd32d4");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210222142601");
user_pref("extensions.lastAppVersion", "86.0");
user_pref("extensions.lastPlatformVersion", "86.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"ab47d725-ac79-42a7-a070-359cb1f40c55\",\"formautofill@mozilla.org\":\"a16801ce-1840-40b4-9c3a-04478b301276\",\"screenshots@mozilla.org\":\"531991d0-72b4-4831-8809-17163f39d493\",\"webcompat-reporter@mozilla.org\":\"17a58235-e3f8-436f-8abc-b94590630eef\",\"webcompat@mozilla.org\":\"bfa04099-1aa0-4ed1-b14b-17c6d27c0f2f\",\"default-theme@mozilla.org\":\"8ed88999-e3fb-4cfc-89a1-cab7ff2bd547\",\"google@search.mozilla.org\":\"8e952eda-4a72-41f3-9017-374e205e5da6\",\"amazondotcom@search.mozilla.org\":\"3ca58495-dace-41b9-a70a-1472e8ca1b10\",\"wikipedia@search.mozilla.org\":\"8e31c91e-3fff-4657-b3c5-d3ca61e45d17\",\"bing@search.mozilla.org\":\"444436d1-d7c6-4ec2-99cf-1401d13fdc82\",\"ddg@search.mozilla.org\":\"dd36e51f-f3bb-4950-bf46-de59beb8381c\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1615291224);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "7e2e9289-4a80-479a-9c13-c34780391759");
user_pref("security.sandbox.plugin.tempDirSuffix", "28df43b6-b384-4199-8fbd-15e037c9e613");
user_pref("toolkit.startup.last_success", 1615291214);
user_pref("toolkit.telemetry.cachedClientID", "8149bace-4f0d-483d-b992-eb12b22ad6da");
user_pref("toolkit.telemetry.previousBuildID", "20210222142601");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
